`timescale 1ns/1ps
module probe_tb;
  reg clk = 0, rst_n = 0, enable = 0, I = 0;
  wire success;
  wire [7:0] O;
  reg bits_mem [0:120];
  integer i;
  integer outfile;

  puzzle dut (.clk(clk), .rst_n(rst_n), .enable(enable), .I(I), .success(success), .O(O));

  always #5 clk = ~clk;

  initial begin
    $readmemb("board.txt", bits_mem);
    rst_n = 0; enable = 0; I = 0;
    repeat (3) @(posedge clk);
    rst_n = 1;
    @(posedge clk);
    enable = 1;
    for (i = 0; i <= 120; i = i + 1) begin
      @(negedge clk);
      I = bits_mem[i];
      @(posedge clk);
    end
    enable = 0;
    I = 0;
    @(posedge clk);
    #1;
    outfile = $fopen("result.txt", "w");
    $fdisplay(outfile, "success=%b", success);
    $fdisplay(outfile, "O=%02x", O);
    $fdisplay(outfile, "s0=%b", dut.state_0);
    $fdisplay(outfile, "s1=%b", dut.state_1);
    $fdisplay(outfile, "s2=%b", dut.state_2);
    $fdisplay(outfile, "s3=%b", dut.state_3);
    $fdisplay(outfile, "s4=%b", dut.state_4);
    $fdisplay(outfile, "s5=%b", dut.state_5);
    $fdisplay(outfile, "s6=%b", dut.state_6);
    $fdisplay(outfile, "s7=%b", dut.state_7);
    $fdisplay(outfile, "s8=%b", dut.state_8);
    $fdisplay(outfile, "s9=%b", dut.state_9);
    $fdisplay(outfile, "s10=%b", dut.state_10);
    $fdisplay(outfile, "s11=%b", dut.state_11);
    $fdisplay(outfile, "s12=%b", dut.state_12);
    $fdisplay(outfile, "s13=%b", dut.state_13);
    $fdisplay(outfile, "s14=%b", dut.state_14);
    $fdisplay(outfile, "s15=%b", dut.state_15);
    $fdisplay(outfile, "s16=%b", dut.state_16);
    $fdisplay(outfile, "s17=%b", dut.state_17);
    $fdisplay(outfile, "s18=%b", dut.state_18);
    $fdisplay(outfile, "s19=%b", dut.state_19);
    $fdisplay(outfile, "s20=%b", dut.state_20);
    $fdisplay(outfile, "s21=%b", dut.state_21);
    $fdisplay(outfile, "s22=%b", dut.state_22);
    $fdisplay(outfile, "s23=%b", dut.state_23);
    $fdisplay(outfile, "s24=%b", dut.state_24);
    $fdisplay(outfile, "s25=%b", dut.state_25);
    $fdisplay(outfile, "s26=%b", dut.state_26);
    $fdisplay(outfile, "s27=%b", dut.state_27);
    $fdisplay(outfile, "s28=%b", dut.state_28);
    $fdisplay(outfile, "s29=%b", dut.state_29);
    $fdisplay(outfile, "s30=%b", dut.state_30);
    $fdisplay(outfile, "s31=%b", dut.state_31);
    $fdisplay(outfile, "s32=%b", dut.state_32);
    $fdisplay(outfile, "s33=%b", dut.state_33);
    $fdisplay(outfile, "s34=%b", dut.state_34);
    $fdisplay(outfile, "s35=%b", dut.state_35);
    $fdisplay(outfile, "s36=%b", dut.state_36);
    $fdisplay(outfile, "s37=%b", dut.state_37);
    $fdisplay(outfile, "s38=%b", dut.state_38);
    $fdisplay(outfile, "s39=%b", dut.state_39);
    $fdisplay(outfile, "s40=%b", dut.state_40);
    $fdisplay(outfile, "s41=%b", dut.state_41);
    $fdisplay(outfile, "s42=%b", dut.state_42);
    $fdisplay(outfile, "s43=%b", dut.state_43);
    $fdisplay(outfile, "s44=%b", dut.state_44);
    $fdisplay(outfile, "s45=%b", dut.state_45);
    $fdisplay(outfile, "s46=%b", dut.state_46);
    $fdisplay(outfile, "s47=%b", dut.state_47);
    $fdisplay(outfile, "s48=%b", dut.state_48);
    $fdisplay(outfile, "s49=%b", dut.state_49);
    $fdisplay(outfile, "s50=%b", dut.state_50);
    $fdisplay(outfile, "s51=%b", dut.state_51);
    $fdisplay(outfile, "s52=%b", dut.state_52);
    $fdisplay(outfile, "s53=%b", dut.state_53);
    $fdisplay(outfile, "s54=%b", dut.state_54);
    $fdisplay(outfile, "s55=%b", dut.state_55);
    $fdisplay(outfile, "s56=%b", dut.state_56);
    $fdisplay(outfile, "s57=%b", dut.state_57);
    $fdisplay(outfile, "s58=%b", dut.state_58);
    $fdisplay(outfile, "s59=%b", dut.state_59);
    $fdisplay(outfile, "s60=%b", dut.state_60);
    $fdisplay(outfile, "s61=%b", dut.state_61);
    $fdisplay(outfile, "s62=%b", dut.state_62);
    $fdisplay(outfile, "s63=%b", dut.state_63);
    $fdisplay(outfile, "s64=%b", dut.state_64);
    $fdisplay(outfile, "s65=%b", dut.state_65);
    $fdisplay(outfile, "s66=%b", dut.state_66);
    $fdisplay(outfile, "s67=%b", dut.state_67);
    $fdisplay(outfile, "s68=%b", dut.state_68);
    $fdisplay(outfile, "s69=%b", dut.state_69);
    $fdisplay(outfile, "s70=%b", dut.state_70);
    $fdisplay(outfile, "s71=%b", dut.state_71);
    $fdisplay(outfile, "s72=%b", dut.state_72);
    $fdisplay(outfile, "s73=%b", dut.state_73);
    $fdisplay(outfile, "s74=%b", dut.state_74);
    $fdisplay(outfile, "s75=%b", dut.state_75);
    $fdisplay(outfile, "s76=%b", dut.state_76);
    $fdisplay(outfile, "s77=%b", dut.state_77);
    $fdisplay(outfile, "s78=%b", dut.state_78);
    $fdisplay(outfile, "s79=%b", dut.state_79);
    $fdisplay(outfile, "s80=%b", dut.state_80);
    $fdisplay(outfile, "s81=%b", dut.state_81);
    $fdisplay(outfile, "s82=%b", dut.state_82);
    $fdisplay(outfile, "s83=%b", dut.state_83);
    $fdisplay(outfile, "s84=%b", dut.state_84);
    $fdisplay(outfile, "s85=%b", dut.state_85);
    $fdisplay(outfile, "s86=%b", dut.state_86);
    $fdisplay(outfile, "s87=%b", dut.state_87);
    $fdisplay(outfile, "s88=%b", dut.state_88);
    $fdisplay(outfile, "s89=%b", dut.state_89);
    $fdisplay(outfile, "s90=%b", dut.state_90);
    $fdisplay(outfile, "s91=%b", dut.state_91);
    $fclose(outfile);
    $finish;
  end
endmodule
